# Generated by Django 5.1.2 on 2024-11-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contebras_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='registrationclassroom',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='student',
            name='curse',
        ),
        migrations.RemoveField(
            model_name='registrationclassroom',
            name='student',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='RegistrationClassroom',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
